#! /bin/bash

mkdir movieAnalyst && cd movieAnalyst
touch joan.txt
#apt update
#apt -y upgrade
apt install -y git
apt install -y nodejs npm
git clone https://github.com/juan-ruiz/movie-analyst-ui.git
#sleep 180
cd movie-analyst-ui
touch adentroPapi.txt
sudo npm -y install
BACK_HOST="10.0.1.2" nodejs server.js