#! /bin/bash
apt update
apt upgrade
mkdir movieAnalystDB && cd movieAnalystDB
touch DBjoan.txt
#apt install -y git
#apt install -y nodejs npm
#Pendiente revisar la configuracion de la instancia de datos.

#Instalacion MySql
apt install -y mariadb-server
gsutil cp gs://movie-analyst-bucket-standar01/table.sql .
mysql -u root < table.sql 
#importar datos o verificar ubicacion
#crear base de datos
#pushear el sql file